import React,{FormEvent,useEffect,useState} from 'react';
import ReactDOM from 'react-dom/client';
import './style.css';

type Vehicle={id:number;title:string;price:number;year?:number;make?:string;model?:string;mileage?:string;image_url?:string;dealer_name:string;dealer_url?:string;distance_miles?:number};
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
function App(){
 const [radius,setRadius]=useState(50),[status,setStatus]=useState(''),[vehicles,setVehicles]=useState<Vehicle[]>([]),[dealerKey,setDealerKey]=useState(localStorage.getItem('gtaDealerKey')||'');
 const load=async(url='/api/vehicles')=>{try{const r=await fetch(url);const v=await r.json();setVehicles(Array.isArray(v)?v:[])}catch{setStatus('Inventory is temporarily unavailable.')}};
 useEffect(()=>{load()},[]);
 const nearby=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(async p=>{setStatus('Finding vehicles near you…');const u=`/api/vehicles?lat=${p.coords.latitude}&lng=${p.coords.longitude}&radius=${radius}`;await load(u);setStatus(`Showing active vehicles within ${radius} miles.`)},()=>setStatus('Location permission was not granted.')):setStatus('Geolocation is not supported by this browser.');
 const signup=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setStatus('Creating dealer account…');const body=Object.fromEntries(f.entries());if(!navigator.geolocation)return setStatus('Location is required for dealer signup.');navigator.geolocation.getCurrentPosition(async p=>{const r=await fetch('/api/dealers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,latitude:p.coords.latitude,longitude:p.coords.longitude})});const j=await r.json();if(!r.ok)return setStatus(j.error||'Signup failed.');localStorage.setItem('gtaDealerKey',j.dealerKey);setDealerKey(j.dealerKey);setStatus('Dealer account created. You can now post up to 3 vehicles free.');e.currentTarget.reset()},()=>setStatus('Allow location access to create your local dealer profile.'))};
 const postVehicle=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),body=Object.fromEntries(f.entries());const r=await fetch('/api/vehicles',{method:'POST',headers:{'Content-Type':'application/json','x-dealer-key':dealerKey},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)return setStatus(j.error||'Unable to post vehicle.');setStatus(`Vehicle posted. ${j.activeCount} of ${j.limit} active listings used.`);e.currentTarget.reset();load()};
 const upgrade=async()=>{const r=await fetch('/api/checkout',{method:'POST',headers:{'x-dealer-key':dealerKey}});const j=await r.json();if(j.url)location.href=j.url;else setStatus(j.error||'Premium checkout unavailable.')};
 return <main>
  <header><div className="brand"><strong>GTA</strong><span>WALL</span></div><a href="#dealers">Dealer Signup</a></header>
  <section className="hero"><div className="badge">GOING TO AUCTION</div><h1>Buy it before<br/><em>the auction does.</em></h1><p>GTA Wall gives buyers a last look at dealer vehicles headed to auction. Dealers get one more chance to sell. Buyers get one more chance to save.</p><div className="actions"><a className="primary" href="#wall">Browse the Wall</a><a className="secondary" href="#dealers">List a Vehicle</a></div></section>
  <section id="wall" className="strip"><b>SHOP LOCAL.</b><span>Find pre-auction vehicles close to you.</span><select value={radius} onChange={e=>setRadius(Number(e.target.value))}><option value="25">25 miles</option><option value="50">50 miles</option><option value="100">100 miles</option><option value="250">250 miles</option></select><button onClick={nearby}>Use My Location</button></section>
  <section className="inventory">{vehicles.length?vehicles.map(v=><article className="vehicle" key={v.id}>{v.image_url&&<img src={v.image_url} alt=""/>}<small>{v.dealer_name}{v.distance_miles!=null?` · ${Math.round(v.distance_miles)} mi`:''}</small><h3>{v.title}</h3><b>{money(v.price)}</b>{v.mileage&&<p>{v.mileage} miles</p>}{v.dealer_url&&<a className="primary" href={v.dealer_url} target="_blank" rel="noreferrer">Visit Dealer →</a>}</article>):<p className="empty">Dealer inventory will appear here as vehicles are posted.</p>}</section>
  <section className="cards"><article><small>FREE</small><h2>Dealer Starter</h2><p>Create a dealer account and display up to <b>3 active vehicles</b> at no charge.</p></article><article><small>$50 / MONTH</small><h2>Premium Dealer</h2><p>Display up to <b>5 active vehicles</b> plus a <b>one-click link</b> from your listings to your dealership website.</p></article><article><small>LOCAL</small><h2>Geo Discovery</h2><p>Buyers can filter active inventory by distance using their current location.</p></article></section>
  <section id="dealers" className="dealer"><h2>{dealerKey?'Dealer Dashboard':'Dealer Signup'}</h2><p><b>Start free.</b> Put vehicles headed to auction in front of local buyers first.</p>{!dealerKey?<form className="form" onSubmit={signup}><input name="name" placeholder="Dealership name" required/><input name="email" type="email" placeholder="Business email" required/><input name="phone" placeholder="Phone"/><input name="address" placeholder="Dealership address" required/><input name="websiteUrl" type="url" placeholder="Dealer website URL"/><button className="primary" type="submit">Create Free Dealer Account</button></form>:<><div className="dashboard"><form className="form" onSubmit={postVehicle}><input name="title" placeholder="Vehicle title e.g. 2022 Ford F-150" required/><input name="price" type="number" min="1" placeholder="Price" required/><input name="year" type="number" placeholder="Year"/><input name="make" placeholder="Make"/><input name="model" placeholder="Model"/><input name="mileage" placeholder="Mileage"/><input name="imageUrl" type="url" placeholder="Vehicle image URL"/><label>Auction deadline<input name="auctionDeadline" type="datetime-local" required/></label><button className="primary" type="submit">Post Vehicle</button></form><aside><h3>Need more exposure?</h3><p>Premium gives your dealership 5 active vehicles and a direct one-click link to your website.</p><button className="primary" onClick={upgrade}>Upgrade — $50/month</button><button className="linkbtn" onClick={()=>{localStorage.removeItem('gtaDealerKey');setDealerKey('');setStatus('Dealer session cleared.')}}>Sign out</button></aside></div></>}</section>
  {status&&<div className="notice">{status}</div>}<footer>GTA WALL · GOING TO AUCTION · gtawall.com</footer>
 </main>
}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
